{{ if .Values.sync.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "eoapi-maps-plugin.fullname" . }}
  labels:
    {{- include "eoapi-maps-plugin.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.sync.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.sync.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.sync.failedJobsHistoryLimit }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: {{ .Values.restartPolicy | default "Never" }}
          containers:
            - name: {{ include "eoapi-maps-plugin.name" . }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["python"]
              args:
                - "scripts/sync.py"
                - {{ .Values.sync.eoapiUrl | required ".Values.sync.eoapiUrl is required." }}
                - {{ .Values.sync.pygeoapiUrl | required ".Values.sync.pygeoapiUrl is required." }}
                - {{ .Values.sync.create | ternary "-c" "" | quote }}
                - {{ .Values.sync.update | ternary "-u" "" | quote }}
                - {{ .Values.sync.delete | ternary "-d" "" | quote }}
                - {{ .Values.sync.forceLinkMimetypeCheck | ternary "-l" "" | quote }}
              env:
                {{- range $key, $value := .Values.env }}
                - name: {{ $key }}
                value: {{ $value | quote }}
                {{- end }}
              {{- with .Values.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
